# Generated by Django 6.1.1 on 2026-09-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliance_type', models.CharField(choices=[('AC', 'Air Conditioner'), ('FRIDGE', 'Refrigerator'), ('WASHING', 'Washing Machine'), ('TV', 'Television'), ('PURIFIER', 'Water Purifier'), ('OTHER', 'Other')], max_length=20)),
                ('brand', models.CharField(max_length=100)),
                ('model_number', models.CharField(max_length=100)),
                ('customer_care_number', models.CharField(blank=True, max_length=20)),
                ('purchase_date', models.DateField()),
                ('bill', models.FileField(blank=True, null=True, upload_to='bills/')),
                ('service_interval_months', models.PositiveIntegerField(default=6)),
            ],
        ),
    ]
