# Generated by Django 6.1.1 on 2026-09-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appliance',
            name='warranty_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
