# Generated by Django 6.1.1 on 2026-09-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0002_appliance_warranty_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='last_service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appliance',
            name='next_service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appliance',
            name='service_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appliance',
            name='service_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
