# Generated by Django 6.1.1 on 2026-09-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0003_appliance_last_service_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
