# Generated by Django 6.1.1 on 2026-09-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0004_appliance_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='maintenance_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
