# Generated by Django 6.1.1 on 2026-09-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0005_appliance_maintenance_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='health_score',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
