# Generated by Django 6.1.1 on 2026-09-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliance_type', models.CharField(choices=[('AC', 'Air Conditioner'), ('FRIDGE', 'Refrigerator'), ('WASHING', 'Washing Machine'), ('TV', 'Television'), ('PURIFIER', 'Water Purifier'), ('OTHER', 'Other')], max_length=20)),
                ('brand', models.CharField(max_length=100)),
                ('model_number', models.CharField(max_length=100)),
                ('customer_care_number', models.CharField(blank=True, max_length=20)),
                ('purchase_date', models.DateField()),
                ('bill', models.FileField(blank=True, null=True, upload_to='bills/')),
                ('service_interval_months', models.PositiveIntegerField(default=6)),
                ('warranty_start_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry_date', models.DateField(blank=True, null=True)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('service_type', models.CharField(blank=True, choices=[('General Service', 'General Service'), ('Cleaning', 'Cleaning'), ('Repair', 'Repair'), ('Gas Filling', 'Gas Filling'), ('Parts Replacement', 'Parts Replacement')], max_length=50)),
                ('service_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
