# Generated by Django 6.1.1 on 2026-09-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='service_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='service_name',
            field=models.CharField(default='General Service', max_length=150),
        ),
    ]
