# Generated by Django 6.1.1 on 2026-09-23 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0010_appliance_other_cost_appliance_repair_cost_and_more'),
        ('service_provider', '0005_servicerequest_other_cost_servicerequest_repair_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='appliance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appliances.appliance'),
        ),
    ]
